// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ButtonSwitchController from "./button_switch_controller"
application.register("button-switch", ButtonSwitchController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReviewController from "./review_controller"
application.register("review", ReviewController)

import SearchBrowseController from "./search_browse_controller"
application.register("search-browse", SearchBrowseController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchThoughtsController from "./search_thoughts_controller"
application.register("search-thoughts", SearchThoughtsController)

import TreeMapController from "./tree_map_controller"
application.register("tree-map", TreeMapController)
